---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
  namespace: container-registry
data:
  htpasswd: |
    admin:$2y$05$9Yul/nIMDWLSRaeQprvovuKPHB5DpEo27UdwYpHHw7tGNbsBoJRzO
  registry-config: |-
     version: 0.1
     log:
       fields:
         service: registry
     storage:
       cache:
         blobdescriptor: inmemory
       swift:
         authurl: https://identity.api.rackspacecloud.com/v2.0/
         username: container-registry
         password: zoZJ8FUTajkH6BUQgwomCaqgpUPBn7gaRi7YATzH
         tenantid: "1095493"
         region: ORD
         container: containers
         rootdirectory: /
     http:
       addr: :5000
       headers:
         X-Content-Type-Options: [nosniff]
     health:
       storagedriver:
         enabled: false
         interval: 10s
         threshold: 3
