sudo: required
language: python
python: "3.6"
services: docker
env:
  global:
    - TESTER_IMAGE_NAME=atst-tester
    - PROD_IMAGE_NAME=atst-prod

before_install:
  - docker login -u $ATAT_DOCKER_REGISTRY_USERNAME -p $ATAT_DOCKER_REGISTRY_PASSWORD $ATAT_DOCKER_REGISTRY_URL
  - docker build --tag "${TESTER_IMAGE_NAME}" . -f docker/tester/Dockerfile

script:
  - docker run "${TESTER_IMAGE_NAME}"

before_deploy:
  - docker build --tag "${PROD_IMAGE_NAME}" . -f docker/prod/Dockerfile
  - remote_image_name="${ATAT_DOCKER_REGISTRY_URL}/${PROD_IMAGE_NAME}:${git_sha}"
  - git_sha="$(git rev-parse --short HEAD)"
  - docker tag "${PROD_IMAGE_NAME}" "${remote_image_name}"
  - docker images
  - docker push "${remote_image_name}"

deploy:
  provider: script
  script: echo "Hi there"
  on:
    all_branches: true
