---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-envvars
  namespace: atat-uat
data:
  TZ: UTC
  FLASK_ENV: dev
  OVERRIDE_CONFIG_FULLPATH: /opt/atat/atst/atst-overrides.ini
  UWSGI_CONFIG_FULLPATH: /opt/atat/atst/uwsgi-config.ini
  RQ_QUEUES: atat-uat
