---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-worker-envvars
data:
  CELERY_DEFAULT_QUEUE: celery-staging
  SERVER_NAME: staging.atat.code.mil
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-envvars
data:
  ASSETS_URL: https://atat-cdn-staging.azureedge.net/
  CELERY_DEFAULT_QUEUE: celery-staging
  STATIC_URL: https://atat-cdn-staging.azureedge.net/static/
