version: 2.0
jobs:
  build:
    docker:
      - image: registry.atat.codes:443/atat-app-builder:circleci
        auth:
          username: $REGISTRY_USERNAME
          password: $REGISTRY_PASSWORD
        environment:
          ATST_PGHOST: localhost
          ATST_PGUSER: root
          ATST_PGDATABASE: circle_test
          PGHOST: localhost
          PGUSER: root
          PGDATABASE: circle_test
      - image: circleci/postgres:9.6.5-alpine-ram
      - image: circleci/redis:4-alpine3.8
    steps:
      - checkout
      - run:
          name: "Clone Submodules"
          command: |
            git submodule update --init --recursive
      - run: ./script/setup
      - run: ./script/cibuild
