---
apiVersion: v1
kind: Namespace
metadata:
  name: atat
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: atst
  name: atst
  namespace: atat
spec:
  selector:
    matchLabels:
      role: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: atst
        role: web
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: atst
          image: pwatat.azurecr.io/atat:884d95ada21a5097f5c07f305d8e4e24d0f2a03f
          resources:
            requests:
               memory: "500Mi"
          envFrom:
          - configMapRef:
              name: atst-envvars
          volumeMounts:
            - name: atst-config
              mountPath: "/opt/atat/atst/atst-overrides.ini"
              subPath: atst-overrides.ini
            - name: nginx-client-ca-bundle
              mountPath: "/opt/atat/atst/ssl/server-certs/ca-chain.pem"
              subPath: client-ca-bundle.pem
            - name: uwsgi-socket-dir
              mountPath: "/var/run/uwsgi"
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8442
              name: main
            - containerPort: 8443
              name: auth
          volumeMounts:
            - name: nginx-config
              mountPath: "/etc/nginx/conf.d/atst.conf"
              subPath: atst.conf
            - name: uwsgi-socket-dir
              mountPath: "/var/run/uwsgi"
            - name: nginx-htpasswd
              mountPath: "/etc/nginx/.htpasswd"
              subPath: .htpasswd
            - name: acme-challenge
              mountPath: "/usr/share/nginx/html/.well-known/acme-challenge/ZZbEjGqx60E5KW9TNZcqyfq4nA8rjD7ay5uP_xxJc9s"
              subPath: ZZbEjGqx60E5KW9TNZcqyfq4nA8rjD7ay5uP_xxJc9s
            - name: acme-auth-challenge
              mountPath: "/usr/share/nginx/html/.well-known/acme-challenge/8pnDhGRBpK28GmYSivrt2CyZLTTL66JhrlL6i5nYbU8"
              subPath: 8pnDhGRBpK28GmYSivrt2CyZLTTL66JhrlL6i5nYbU8
      volumes:
        - name: atst-config
          secret:
            secretName: atst-config-ini
            items:
            - key: override.ini
              path: atst-overrides.ini
              mode: 0644
        - name: nginx-client-ca-bundle
          secret:
            secretName: nginx-client-ca-bundle
            items:
            - key: client-ca-bundle.pem
              path: client-ca-bundle.pem
              mode: 0666
        - name: nginx-config
          configMap:
            name: atst-nginx
            items:
            - key: nginx-config
              path: atst.conf
        - name: uwsgi-socket-dir
          emptyDir:
            medium: Memory
        - name: nginx-htpasswd
          secret:
            secretName: atst-nginx-htpasswd
            items:
            - key: htpasswd
              path: .htpasswd
              mode: 0640
        - name: acme-challenge
          secret:
            secretName: acme
            items:
            - key: ZZbEjGqx60E5KW9TNZcqyfq4nA8rjD7ay5uP_xxJc9s
              path: ZZbEjGqx60E5KW9TNZcqyfq4nA8rjD7ay5uP_xxJc9s
              mode: 0666
        - name: acme-auth-challenge
          secret:
            secretName: acme-auth
            items:
            - key: 8pnDhGRBpK28GmYSivrt2CyZLTTL66JhrlL6i5nYbU8
              path: 8pnDhGRBpK28GmYSivrt2CyZLTTL66JhrlL6i5nYbU8
              mode: 0666
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: atst
  name: atst-worker
  namespace: atat
spec:
  selector:
    matchLabels:
      role: worker
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: atst
        role: worker
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: atst-worker
          image: pwatat.azurecr.io/atat:884d95ada21a5097f5c07f305d8e4e24d0f2a03f
          args: [
            "/opt/atat/atst/.venv/bin/python",
            "/opt/atat/atst/.venv/bin/flask",
            "rq",
            "worker"
          ]
          resources:
            requests:
               memory: "500Mi"
          envFrom:
          - configMapRef:
              name: atst-envvars
          - configMapRef:
              name: atst-worker-envvars
          volumeMounts:
            - name: atst-config
              mountPath: "/opt/atat/atst/atst-overrides.ini"
              subPath: atst-overrides.ini
      volumes:
        - name: atst-config
          secret:
            secretName: atst-config-ini
            items:
            - key: override.ini
              path: atst-overrides.ini
              mode: 0644
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: atst
  name: atst-main
  namespace: atat
spec:
  loadBalancerIP: 13.92.235.6
  ports:
  - port: 80
    targetPort: 8442
  selector:
    role: web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: atst
  name: atst-auth
  namespace: atat
spec:
  loadBalancerIP: 23.100.24.41
  ports:
  - port: 80
    targetPort: 8443
  selector:
    role: web
  type: LoadBalancer
