---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-envvars
  namespace: atat
data:
  FLASK_ENV: dev
  OVERRIDE_CONFIG_FULLPATH: /opt/atat/atst/atst-overrides.ini
  UWSGI_CONFIG_FULLPATH: /opt/atat/atst/uwsgi-config.ini
