---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: atat-kv-identity
spec:
  type: 0
  ResourceID: $KV_MI_ID
  ClientID: $KV_MI_CLIENT_ID
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: atat-key-vault-identity-binding
spec:
  AzureIdentity: atat-kv-identity
  Selector: atat-kv-id-binding
---

