---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-envvars
  namespace: atat
data:
  TZ: UTC
  FLASK_ENV: dev
  OVERRIDE_CONFIG_FULLPATH: /opt/atat/atst/atst-overrides.ini
  UWSGI_CONFIG_FULLPATH: /opt/atat/atst/uwsgi.ini
  LOG_JSON: "true"
  CSP: azure
  PGSSLMODE: verify-full
  PGSSLROOTCERT: /opt/atat/atst/ssl/pgsslrootcert.crt
