---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-envvars
  namespace: atat
data:
  CSP: azure
  CELERY_DEFAULT_QUEUE: celery-master
  FLASK_ENV: dev
  LOG_JSON: "true"
  OVERRIDE_CONFIG_FULLPATH: /opt/atat/atst/atst-overrides.ini
  PGSSLMODE: verify-full
  PGSSLROOTCERT: /opt/atat/atst/ssl/pgsslrootcert.crt
  TZ: UTC
  UWSGI_CONFIG_FULLPATH: /opt/atat/atst/uwsgi.ini
