---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-worker-envvars
  namespace: atat
data:
  TZ: UTC
  DISABLE_CRL_CHECK: "True"
  SERVER_NAME: azure.atat.code.mil
  PGSSLMODE: verify-full
  PGSSLROOTCERT: /opt/atat/atst/ssl/pgsslrootcert.crt
