---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-worker-envvars
  namespace: atat
data:
  CELERY_DEFAULT_QUEUE: celery-master
  DISABLE_CRL_CHECK: "True"
  PGSSLMODE: verify-full
  PGSSLROOTCERT: /opt/atat/atst/ssl/pgsslrootcert.crt
  SERVER_NAME: azure.atat.code.mil
  TZ: UTC
