apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crls-vol-claim
  namespace: atat
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
